services:
  - type: web
    name: remote-control-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.app:app --bind 0.0.0.0:$PORT --workers 1 --worker-class gevent --worker-connections 1000 --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0